[project]
name = "leo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beancount>=3.2.0",
    "fava>=1.30.9",
    "fava-dashboards>=1.2.2",
    "tatsu-lts==5.14.0",
]
